# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hNb8KzgguTSjikc0hZSE8R5xeK5DwGqR
"""

from flask import Flask, request
from sklearn.linear_model import LogisticRegression
import requests
from google.cloud import storage
import pickle

app = Flask(__name__)

get_score = pickle.load(open("similarity.pkl","rb"))


@app.route('/api_predict', methods = ['POST','GET'])
def api_predict():
    if request.method == 'GET':
        return "Please Send POST Request"
    elif request.method == 'POST':
        
        print("Hello" + str(request.get_json()))
        
        data = request.get_json()
        text1=data["text1"]
        text2=data["text2"]
        similarity_score= get_score(text1,text2)
        return str(similarity_score)
        

if __name__ == "__main__":
    app.run()
    